name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.3.0
  equatable: ^2.0.3
  flutter_bloc: ^7.3.0
  google_fonts: ^2.1.0
  hydrated_bloc: ^7.1.0
  path_provider: ^2.0.3
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  bloc_test: ^8.3.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
